language: php
install:
  - travis_retry composer self-update
  - composer install
  - travis_wait ./test/run.sh prepare
script: ./test/run.sh single
php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm
cache:
  directories:
    - $HOME/.composer/cache
    - test/functional/_cache
env:
  - LARAVEL_VERSION=4.0
  - LARAVEL_VERSION=4.1
  - LARAVEL_VERSION=4.2
  - LARAVEL_VERSION=5.0
  - LARAVEL_VERSION=5.1
matrix:
  fast_finish: true
