language: php
install:
  - composer self-update
  - composer install
  - ./test/run.sh prepare
script: ./test/run.sh single
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
env:
  - LARAVEL_VERSION=4.0
  - LARAVEL_VERSION=4.1
  - LARAVEL_VERSION=4.2
  - LARAVEL_VERSION=5.0
  - LARAVEL_VERSION=5.1
matrix:
  exclude:
    - php: 5.3
      env: LARAVEL_VERSION=4.2
    - php: 5.3
      env: LARAVEL_VERSION=5.0
    - php: 5.3
      env: LARAVEL_VERSION=5.1
    - php: 5.4
      env: LARAVEL_VERSION=5.1
